// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © xobiccc

//@version=5
indicator("MA Crosses", overlay = true)

// User inputs
ema_period1 = input.int(defval = 8, title = "Shorter EMA")
ema_period2 = input.int(defval = 20, title = "Longer EMA")

// Get EMAs
ema1 = ta.ema(close,ema_period1)
ema2 = ta.ema(close,ema_period2)

// Get Crosses
ma_cross_over = ta.crossover(ema1, ema2)
ma_cross_under = ta.crossunder(ema1, ema2)

// Alerts
if ma_cross_over
    alert(message = "Crossover of " + str.tostring(ema_period1) + " vs " + str.tostring(ema_period2) + "on {{ticker}}", freq = alert.freq_once_per_bar )
if ma_cross_under
    alert(message = "Crossunder of " + str.tostring(ema_period1) + " vs " + str.tostring(ema_period2) + "on {{ticker}}", freq = alert.freq_once_per_bar )


//Draw EMAs
plot(ema1, color = color.green)
plot(ema2, color = color.red)

//Draw crosses
bgcolor(ma_cross_over ? color.green : na)
bgcolor(ma_cross_under ? color.red : na)
